#!/bin/bash

# Variables
RESOURCE_GROUP="EcommerceResourceGroup"
LOCATION="eastus"
VM_NAME="EcommerceVM"
IMAGE="UbuntuLTS"
ADMIN_USERNAME="adminuser"
ADMIN_PASSWORD="SecurePassword123!"
DISK1_NAME="DataDisk1"
DISK2_NAME="DataDisk2"
DISK_SIZE_GB=1024  # 1 TB en GB

# Crear un grupo de recursos
az group create --name $RESOURCE_GROUP --location $LOCATION

# Crear una máquina virtual
az vm create \
  --resource-group $RESOURCE_GROUP \
  --name $VM_NAME \
  --image $IMAGE \
  --admin-username $ADMIN_USERNAME \
  --admin-password $ADMIN_PASSWORD \
  --size Standard_D4s_v3 \  # Tamaño de la VM (ajusta según tus necesidades)
  --generate-ssh-keys

# Crear dos discos de 1 TB
az disk create \
  --resource-group $RESOURCE_GROUP \
  --name $DISK1_NAME \
  --size-gb $DISK_SIZE_GB \
  --sku Premium_LRS
